spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 575441009169-rk7op3ge71meeihjnri6lqgb3ovsua7p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid
              - https://www.googleapis.com/auth/contacts
      resourceserver:
        opaque-token:
          client-id: 575441009169-rk7op3ge71meeihjnri6lqgb3ovsua7p.apps.googleusercontent.com
          client-secret: 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
        opaquetoken:
          introspection-uri: https://www.googleapis.com/oauth2/v3/userinfo